# Generated by Django 2.1.7 on 2019-03-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (0, 'Unknown')])),
                ('profession', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('qq', models.CharField(max_length=128, verbose_name='QQ')),
                ('phone', models.CharField(max_length=128)),
                ('status', models.IntegerField(choices=[(0, 'Apply'), (1, 'Pass'), (2, 'Denine')], default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
